spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/userservice}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  liquibase:
    change-log: classpath:db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true